//
//  WindowActionSession.swift
//  Line
//
//  Created by Codex on 2026-07-08.
//

import AppKit
import Defaults
import SwiftUI

@MainActor
protocol WindowActionInterception {
    func intercept(_ action: BoundWindowAction, screen: NSScreen) -> Bool
}

struct StashWindowActionInterception: WindowActionInterception {
    func intercept(_ action: BoundWindowAction, screen: NSScreen) -> Bool {
        StashManager.shared.handleIfStashed(action, screen: screen)
    }
}

enum ScreenSwitchActionPolicy {
    static let autogeneratedActionName = "autogenerated_screen_switching_action"

    static func targetScreen(for action: WindowAction.ScreenSwitchAction, from currentScreen: NSScreen) -> NSScreen? {
        switch action {
        case .next:
            ScreenUtility.nextScreen(from: currentScreen)
        case .previous:
            ScreenUtility.previousScreen(from: currentScreen)
        case .left:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .left)
        case .right:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .right)
        case .top:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .top)
        case .bottom:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .bottom)
        }
    }

    static func preservingCurrentFrameAction(for window: Window, on currentScreen: NSScreen) -> BoundWindowAction {
        let adjustedBounds = PaddingConfiguration
            .getConfiguredPadding(for: currentScreen)
            .applyToBounds(currentScreen.cgSafeScreenFrame, screen: currentScreen)

        let proportionalFrame = proportionalFrame(for: window.frame, within: adjustedBounds)
        let customAction = WindowAction.CustomWindowAction(
            name: autogeneratedActionName,
            unit: .percentage,
            anchor: .topLeft,
            sizeMode: .custom,
            width: proportionalFrame.width * 100,
            height: proportionalFrame.height * 100,
            positionMode: .coordinates,
            xPoint: proportionalFrame.minX * 100,
            yPoint: proportionalFrame.minY * 100
        )

        return BoundWindowAction(
            action: .custom(customAction),
            keybind: []
        )
    }

    static func proportionalFrame(for windowFrame: CGRect, within adjustedBounds: CGRect) -> CGRect {
        CGRect(
            x: (windowFrame.minX - adjustedBounds.minX) / adjustedBounds.width,
            y: (windowFrame.minY - adjustedBounds.minY) / adjustedBounds.height,
            width: windowFrame.width / adjustedBounds.width,
            height: windowFrame.height / adjustedBounds.height
        )
    }
}

@MainActor
final class WindowActionSession {
    private(set) var context: ResizeContext

    private let interception: (any WindowActionInterception)?

    init(
        context: ResizeContext,
        interception: (any WindowActionInterception)? = nil
    ) {
        self.context = context
        self.interception = interception
    }

    func replaceContext(_ context: ResizeContext) {
        self.context = context
    }

    var hasParentCycleAction: Bool {
        context.parentAction != nil
    }

    struct Input {
        var triggeredFromScreenChange: Bool
        var disableHapticFeedback: Bool
        var canAdvanceCycle: Bool
        var isReverseCycleRequested: Bool

        init(
            triggeredFromScreenChange: Bool = false,
            disableHapticFeedback: Bool = false,
            canAdvanceCycle: Bool = true,
            isReverseCycleRequested: Bool = false
        ) {
            self.triggeredFromScreenChange = triggeredFromScreenChange
            self.disableHapticFeedback = disableHapticFeedback
            self.canAdvanceCycle = canAdvanceCycle
            self.isReverseCycleRequested = isReverseCycleRequested
        }
    }

    struct ChangeResult {
        struct Continuation {
            let action: BoundWindowAction
        }

        let isIgnored: Bool
        let wasIntercepted: Bool
        let shouldRestartTimeout: Bool
        let shouldUpdateIndicators: Bool
        let shouldApplyImmediately: Bool
        let shouldApplyFocusAction: Bool
        let shouldPerformHapticFeedback: Bool
        let continuation: Continuation?

        static let ignored = ChangeResult(
            isIgnored: true,
            wasIntercepted: false,
            shouldRestartTimeout: false,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static let intercepted = ChangeResult(
            isIgnored: false,
            wasIntercepted: true,
            shouldRestartTimeout: false,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static let timeoutOnly = ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static func hapticOnly(disabled: Bool) -> ChangeResult {
            ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: false,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: !disabled,
                continuation: nil
            )
        }
    }

    func changeAction(
        _ requestedAction: BoundWindowAction,
        input: Input
    ) async -> ChangeResult {
        guard let currentScreen = context.screen ?? resolveAndStoreTargetScreen(
            action: requestedAction,
            window: context.window
        ) else {
            return .ignored
        }

        if interception?.intercept(requestedAction, screen: currentScreen) == true {
            return .intercepted
        }

        guard context.action.id != requestedAction.id || requestedAction.canRepeat else {
            return .ignored
        }

        var newAction = requestedAction
        var newParentAction: BoundWindowAction?

        if case let .cycle(cycleActions) = requestedAction.action {
            newParentAction = requestedAction

            guard !cycleActions.isEmpty else {
                return .ignored
            }

            if input.canAdvanceCycle {
                newAction = await getNextCycleAction(
                    requestedAction,
                    isReverseCycleRequested: input.isReverseCycleRequested
                )
            } else {
                let cycleBoundActions = cycleActions.map { BoundWindowAction(action: $0, keybind: []) }
                if !cycleBoundActions.contains(where: { $0.action == context.action.action }) {
                    newAction = cycleBoundActions.first ?? BoundWindowAction(action: .special(.noAction), keybind: [])
                } else {
                    newAction = context.action
                }

                if newAction.action == context.action.action {
                    return .timeoutOnly
                }
            }

            if input.triggeredFromScreenChange, newAction.willChangeScreen {
                return .hapticOnly(disabled: input.disableHapticFeedback)
            }
        }

        if newAction.willChangeScreen {
            return await changeScreen(
                action: newAction,
                parentAction: newParentAction,
                currentScreen: currentScreen,
                input: input
            )
        }

        let shouldPerformHapticFeedback = !input.disableHapticFeedback

        guard newAction.action != context.action.action || newAction.canRepeat else {
            return ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: false,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: shouldPerformHapticFeedback,
                continuation: nil
            )
        }

        let previousActionWasNoOp = context.action.isNoOp
        setAction(to: newAction, parent: newParentAction)

        if !Defaults[.previewVisibility], !previousActionWasNoOp {
            await context.refreshResolvedState()
        }

        return ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: true,
            shouldApplyImmediately: !Defaults[.previewVisibility],
            shouldApplyFocusAction: newAction.willFocusWindow,
            shouldPerformHapticFeedback: shouldPerformHapticFeedback,
            continuation: nil
        )
    }

    private func changeScreen(
        action newAction: BoundWindowAction,
        parentAction newParentAction: BoundWindowAction?,
        currentScreen: NSScreen,
        input: Input
    ) async -> ChangeResult {
        let newScreen: NSScreen = if case let .screen(screenAction) = newAction.action,
                                     let targetScreen = ScreenSwitchActionPolicy.targetScreen(for: screenAction, from: currentScreen) {
            targetScreen
        } else {
            currentScreen
        }

        if context.action.isNoOp || context.action.willManipulateExistingWindowFrame {
            if let targetWindow = context.window {
                if let lastAction = await WindowRecords.shared.getCurrentAction(for: targetWindow),
                   lastAction.getActionName() != ScreenSwitchActionPolicy.autogeneratedActionName {
                    setAction(to: lastAction, parent: nil)
                } else {
                    setAction(
                        to: ScreenSwitchActionPolicy.preservingCurrentFrameAction(for: targetWindow, on: currentScreen),
                        parent: nil
                    )
                }
            } else {
                setAction(to: BoundWindowAction(action: .standard(.center(.macOS)), keybind: []), parent: nil)
            }
        }

        context.setScreen(to: newScreen)

        if let parent = newParentAction {
            setAction(to: newAction, parent: parent)
            return ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: true,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: false,
                continuation: .init(action: parent)
            )
        }

        let shouldApplyImmediately = !Defaults[.previewVisibility]

        return ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: true,
            shouldApplyImmediately: shouldApplyImmediately,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: shouldApplyImmediately && !input.disableHapticFeedback,
            continuation: nil
        )
    }

    private func getNextCycleAction(
        _ action: BoundWindowAction,
        isReverseCycleRequested: Bool
    ) async -> BoundWindowAction {
        guard case let .cycle(cycleActions) = action.action else {
            return action
        }

        let currentCycle = cycleActions.map { BoundWindowAction(action: $0, keybind: []) }
        guard let firstCycleAction = currentCycle.first else {
            return BoundWindowAction(action: .special(.noAction), keybind: [])
        }

        let allowReverseCycle = !action.keybind.contains(CGKeyCode.kVK_Shift)
            && Defaults[.triggerKey].contains(.kVK_Shift) == false
            && Defaults[.cycleBackwardsOnShiftPressed]

        let shouldCycleBackwards = allowReverseCycle && isReverseCycleRequested
        var currentIndex: Int?

        if Defaults[.cycleModeRestartEnabled],
           context.action.direction == .noSelection || !currentCycle.contains(where: { $0.action == context.action.action }) {
            return firstCycleAction
        }

        if context.action.direction == .noSelection,
           !currentCycle.contains(where: { $0.action == context.action.action }),
           let window = context.window,
           let latestRecord = await WindowRecords.shared.getCurrentAction(for: window) {
            currentIndex = currentCycle.firstIndex(where: { $0.action == latestRecord.action })
        } else {
            currentIndex = currentCycle.firstIndex(where: { $0.action == context.action.action })
        }

        guard var nextIndex = currentIndex else {
            return firstCycleAction
        }

        nextIndex += shouldCycleBackwards ? -1 : 1

        if nextIndex >= currentCycle.count {
            nextIndex = 0
        }

        if nextIndex < 0 {
            nextIndex = currentCycle.count - 1
        }

        return currentCycle[nextIndex]
    }

    private func setAction(to newAction: BoundWindowAction, parent newParentAction: BoundWindowAction?) {
        context.setAction(to: newAction, parent: newParentAction)
    }

    private func resolveAndStoreTargetScreen(action: BoundWindowAction, window: Window?) -> NSScreen? {
        var targetScreen = Defaults[.useScreenWithCursor] ? NSScreen.screenWithMouse : NSScreen.main

        if action.willChangeScreen,
           let window,
           let screen = ScreenUtility.screenContaining(window) {
            targetScreen = screen
        }

        if let targetScreen {
            context.setScreen(to: targetScreen)
        }

        return targetScreen
    }
}
