//
//  WindowActionSession.swift
//  Line
//
//  Created by Codex on 2026-07-08.
//

import AppKit
import Defaults
import SwiftUI

@MainActor
protocol WindowActionInterception {
    func intercept(_ action: BoundWindowAction, screen: NSScreen) -> Bool
}

struct StashWindowActionInterception: WindowActionInterception {
    func intercept(_ action: BoundWindowAction, screen: NSScreen) -> Bool {
        StashManager.shared.handleIfStashed(action, screen: screen)
    }
}

enum ScreenSwitchActionPolicy {
    static let autogeneratedActionName = "autogenerated_screen_switching_action"

    static func targetScreen(for action: WindowAction.ScreenSwitchAction, from currentScreen: NSScreen) -> NSScreen? {
        switch action {
        case .next:
            ScreenUtility.nextScreen(from: currentScreen)
        case .previous:
            ScreenUtility.previousScreen(from: currentScreen)
        case .left:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .left)
        case .right:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .right)
        case .top:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .top)
        case .bottom:
            ScreenUtility.directionalScreen(from: currentScreen, direction: .bottom)
        }
    }

    static func preservingCurrentFrameAction(for window: Window, on currentScreen: NSScreen) -> BoundWindowAction {
        let adjustedBounds = PaddingConfiguration
            .getConfiguredPadding(for: currentScreen)
            .applyToBounds(currentScreen.cgSafeScreenFrame, screen: currentScreen)

        let proportionalFrame = proportionalFrame(for: window.frame, within: adjustedBounds)
        let customAction = WindowAction.CustomWindowAction(
            name: autogeneratedActionName,
            unit: .percentage,
            anchor: .topLeft,
            sizeMode: .custom,
            width: proportionalFrame.width * 100,
            height: proportionalFrame.height * 100,
            positionMode: .coordinates,
            xPoint: proportionalFrame.minX * 100,
            yPoint: proportionalFrame.minY * 100
        )

        return BoundWindowAction(
            action: .custom(customAction),
            keybind: []
        )
    }

    static func proportionalFrame(for windowFrame: CGRect, within adjustedBounds: CGRect) -> CGRect {
        CGRect(
            x: (windowFrame.minX - adjustedBounds.minX) / adjustedBounds.width,
            y: (windowFrame.minY - adjustedBounds.minY) / adjustedBounds.height,
            width: windowFrame.width / adjustedBounds.width,
            height: windowFrame.height / adjustedBounds.height
        )
    }
}

@MainActor
final class WindowActionSession {
    /// Layout truth for this interaction — immutable Prepared Resize snapshots.
    private(set) var preparedResize: WindowResizeExecution.PreparedResize

    private let interception: (any WindowActionInterception)?

    init(
        preparedResize: WindowResizeExecution.PreparedResize,
        interception: (any WindowActionInterception)? = nil
    ) {
        self.preparedResize = preparedResize
        self.interception = interception
    }

    func replacePreparedResize(_ preparedResize: WindowResizeExecution.PreparedResize) {
        self.preparedResize = preparedResize
    }

    var hasParentCycleAction: Bool {
        preparedResize.parentAction != nil
    }

    var action: BoundWindowAction { preparedResize.action }
    var parentAction: BoundWindowAction? { preparedResize.parentAction }
    var window: Window? { preparedResize.window }
    var screen: NSScreen { preparedResize.screen }

    struct Input {
        var triggeredFromScreenChange: Bool
        var disableHapticFeedback: Bool
        var canAdvanceCycle: Bool
        var isReverseCycleRequested: Bool

        init(
            triggeredFromScreenChange: Bool = false,
            disableHapticFeedback: Bool = false,
            canAdvanceCycle: Bool = true,
            isReverseCycleRequested: Bool = false
        ) {
            self.triggeredFromScreenChange = triggeredFromScreenChange
            self.disableHapticFeedback = disableHapticFeedback
            self.canAdvanceCycle = canAdvanceCycle
            self.isReverseCycleRequested = isReverseCycleRequested
        }
    }

    struct ChangeResult {
        struct Continuation {
            let action: BoundWindowAction
        }

        let isIgnored: Bool
        let wasIntercepted: Bool
        let shouldRestartTimeout: Bool
        let shouldUpdateIndicators: Bool
        let shouldApplyImmediately: Bool
        let shouldApplyFocusAction: Bool
        let shouldPerformHapticFeedback: Bool
        let continuation: Continuation?

        static let ignored = ChangeResult(
            isIgnored: true,
            wasIntercepted: false,
            shouldRestartTimeout: false,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static let intercepted = ChangeResult(
            isIgnored: false,
            wasIntercepted: true,
            shouldRestartTimeout: false,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static let timeoutOnly = ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: false,
            shouldApplyImmediately: false,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: false,
            continuation: nil
        )

        static func hapticOnly(disabled: Bool) -> ChangeResult {
            ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: false,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: !disabled,
                continuation: nil
            )
        }
    }

    func changeAction(
        _ requestedAction: BoundWindowAction,
        input: Input
    ) async -> ChangeResult {
        guard let currentScreen = resolveTargetScreen(
            action: requestedAction,
            window: preparedResize.window,
            fallback: preparedResize.screen
        ) else {
            return .ignored
        }

        if interception?.intercept(requestedAction, screen: currentScreen) == true {
            return .intercepted
        }

        guard preparedResize.action.id != requestedAction.id || requestedAction.canRepeat else {
            return .ignored
        }

        var newAction = requestedAction
        var newParentAction: BoundWindowAction?

        if case let .cycle(cycleActions) = requestedAction.action {
            newParentAction = requestedAction

            guard !cycleActions.isEmpty else {
                return .ignored
            }

            if input.canAdvanceCycle {
                newAction = await getNextCycleAction(
                    requestedAction,
                    isReverseCycleRequested: input.isReverseCycleRequested
                )
            } else {
                let cycleBoundActions = cycleActions.map { BoundWindowAction(action: $0, keybind: []) }
                if !cycleBoundActions.contains(where: { $0.action == preparedResize.action.action }) {
                    newAction = cycleBoundActions.first ?? BoundWindowAction(action: .special(.noAction), keybind: [])
                } else {
                    newAction = preparedResize.action
                }

                if newAction.action == preparedResize.action.action {
                    return .timeoutOnly
                }
            }

            if input.triggeredFromScreenChange, newAction.willChangeScreen {
                return .hapticOnly(disabled: input.disableHapticFeedback)
            }
        }

        if newAction.willChangeScreen {
            return await changeScreen(
                action: newAction,
                parentAction: newParentAction,
                currentScreen: currentScreen,
                input: input
            )
        }

        let shouldPerformHapticFeedback = !input.disableHapticFeedback

        guard newAction.action != preparedResize.action.action || newAction.canRepeat else {
            return ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: false,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: shouldPerformHapticFeedback,
                continuation: nil
            )
        }

        applyTransition(to: newAction, parent: newParentAction)

        return ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: true,
            shouldApplyImmediately: !Defaults[.previewVisibility],
            shouldApplyFocusAction: newAction.willFocusWindow,
            shouldPerformHapticFeedback: shouldPerformHapticFeedback,
            continuation: nil
        )
    }

    private func changeScreen(
        action newAction: BoundWindowAction,
        parentAction newParentAction: BoundWindowAction?,
        currentScreen: NSScreen,
        input: Input
    ) async -> ChangeResult {
        let newScreen: NSScreen = if case let .screen(screenAction) = newAction.action,
                                     let targetScreen = ScreenSwitchActionPolicy.targetScreen(for: screenAction, from: currentScreen) {
            targetScreen
        } else {
            currentScreen
        }

        // When current action has no meaningful frame, pick a frame-preserving action first.
        var base = preparedResize
        if preparedResize.action.isNoOp || preparedResize.action.willManipulateExistingWindowFrame {
            let frameAction: BoundWindowAction
            if let targetWindow = preparedResize.window {
                if let lastAction = await WindowRecords.shared.getCurrentAction(for: targetWindow),
                   lastAction.getActionName() != ScreenSwitchActionPolicy.autogeneratedActionName {
                    frameAction = lastAction
                } else {
                    frameAction = ScreenSwitchActionPolicy.preservingCurrentFrameAction(
                        for: targetWindow,
                        on: currentScreen
                    )
                }
            } else {
                frameAction = BoundWindowAction(action: .standard(.center(.macOS)), keybind: [])
            }
            base = WindowResizeExecution.transition(from: preparedResize, toAction: frameAction, parentAction: nil)
            preparedResize = base
        }

        if let parent = newParentAction {
            preparedResize = WindowResizeExecution.transition(
                from: base,
                toAction: newAction,
                parentAction: parent,
                screen: newScreen
            )
            return ChangeResult(
                isIgnored: false,
                wasIntercepted: false,
                shouldRestartTimeout: true,
                shouldUpdateIndicators: true,
                shouldApplyImmediately: false,
                shouldApplyFocusAction: false,
                shouldPerformHapticFeedback: false,
                continuation: .init(action: parent)
            )
        }

        preparedResize = WindowResizeExecution.transition(
            from: base,
            toAction: base.action,
            parentAction: base.parentAction,
            screen: newScreen
        )

        let shouldApplyImmediately = !Defaults[.previewVisibility]

        return ChangeResult(
            isIgnored: false,
            wasIntercepted: false,
            shouldRestartTimeout: true,
            shouldUpdateIndicators: true,
            shouldApplyImmediately: shouldApplyImmediately,
            shouldApplyFocusAction: false,
            shouldPerformHapticFeedback: shouldApplyImmediately && !input.disableHapticFeedback,
            continuation: nil
        )
    }

    private func getNextCycleAction(
        _ action: BoundWindowAction,
        isReverseCycleRequested: Bool
    ) async -> BoundWindowAction {
        guard case let .cycle(cycleActions) = action.action else {
            return action
        }

        let currentCycle = cycleActions.map { BoundWindowAction(action: $0, keybind: []) }
        guard let firstCycleAction = currentCycle.first else {
            return BoundWindowAction(action: .special(.noAction), keybind: [])
        }

        let allowReverseCycle = !action.keybind.contains(CGKeyCode.kVK_Shift)
            && Defaults[.triggerKey].contains(.kVK_Shift) == false
            && Defaults[.cycleBackwardsOnShiftPressed]

        let shouldCycleBackwards = allowReverseCycle && isReverseCycleRequested
        var currentIndex: Int?

        if Defaults[.cycleModeRestartEnabled],
           preparedResize.action.direction == .noSelection
           || !currentCycle.contains(where: { $0.action == preparedResize.action.action }) {
            return firstCycleAction
        }

        if preparedResize.action.direction == .noSelection,
           !currentCycle.contains(where: { $0.action == preparedResize.action.action }),
           let window = preparedResize.window,
           let latestRecord = await WindowRecords.shared.getCurrentAction(for: window) {
            currentIndex = currentCycle.firstIndex(where: { $0.action == latestRecord.action })
        } else {
            currentIndex = currentCycle.firstIndex(where: { $0.action == preparedResize.action.action })
        }

        guard var nextIndex = currentIndex else {
            return firstCycleAction
        }

        nextIndex += shouldCycleBackwards ? -1 : 1

        if nextIndex >= currentCycle.count {
            nextIndex = 0
        }

        if nextIndex < 0 {
            nextIndex = currentCycle.count - 1
        }

        return currentCycle[nextIndex]
    }

    private func applyTransition(to newAction: BoundWindowAction, parent newParentAction: BoundWindowAction?) {
        preparedResize = WindowResizeExecution.transition(
            from: preparedResize,
            toAction: newAction,
            parentAction: newParentAction
        )
    }

    private func resolveTargetScreen(
        action: BoundWindowAction,
        window: Window?,
        fallback: NSScreen?
    ) -> NSScreen? {
        var targetScreen = Defaults[.useScreenWithCursor] ? NSScreen.screenWithMouse : NSScreen.main
        targetScreen = targetScreen ?? fallback

        if action.willChangeScreen,
           let window,
           let screen = ScreenUtility.screenContaining(window) {
            targetScreen = screen
        }

        return targetScreen
    }
}
