//
//  WindowRecords.swift
//  Line
//
//  Created by nnecec on 2023-09-23.
//

import Scribe
import SwiftUI

@Loggable
actor WindowRecords {
    nonisolated static let shared = WindowRecords()

    private var recordsByWindowID: [CGWindowID: WindowRecords.Record] = [:]

    struct Record {
        let initialFrame: CGRect
        var actions: [BoundWindowAction]

        init(initialFrame: CGRect) {
            self.initialFrame = initialFrame
            self.actions = [BoundWindowAction(action: .special(.initialFrame), keybind: [])]
        }
    }

    /// Pre-resolved snapshot of a window's records for synchronous access.
    struct ResolvedRecord {
        let initialFrame: CGRect?
        let lastAction: BoundWindowAction?

        init(for window: Window) async {
            self.initialFrame = await WindowRecords.shared.getInitialFrame(for: window)
            self.lastAction = await WindowRecords.shared.getLastAction(for: window)
        }
    }

    /// Erase all previous records for a window
    /// - Parameter window: Window to erase
    func eraseRecords(for window: Window) {
        guard recordsByWindowID[window.cgWindowID] != nil else {
            // Records don't exist
            return
        }

        recordsByWindowID[window.cgWindowID] = nil
        log.info("Erased records for: \(window)")
    }

    /// Records the window's initial frame if no record exists yet.
    /// - Parameters:
    ///   - window: the window to record.
    ///   - resolvedProperties: pre-resolved properties to avoid redundant AX calls. Falls back to `window.frame` if nil.
    func recordFirstIfNeeded(for window: Window, resolvedProperties: Window.ResolvedProperties?) {
        guard recordsByWindowID[window.cgWindowID] == nil else { return }
        recordsByWindowID[window.cgWindowID] = Record(initialFrame: resolvedProperties?.frame ?? window.frame)
        log.info("Recorded first for: \(window)")
    }

    /// Determines if an action should be recorded using its frame instead of the action applied onto it.
    /// - Parameter action: the action to apply onto the window.
    /// - Returns: Whether this action should be recorded with its final frame instead of using the action.
    nonisolated func shouldStoreAsFinalFrame(_ action: BoundWindowAction) -> Bool {
        // Actions that are stored as frames need to be recorded *after* resize.
        // These actions are context-dependent, and cannot simply be called as an action to restore the previous state.
        let storeAsFrame = action.willChangeScreen ||
            action.willManipulateExistingWindowFrame ||
            action.isGridLayoutAction
        return storeAsFrame
    }

    /// Record a window's action in the records array.
    /// - Parameters:
    ///   - window: Window to record.
    ///   - resolvedProperties: pre-resolved properties to avoid redundant AX calls. Falls back to `window.frame` if nil.
    ///   - action: BoundWindowAction to record.
    func record(_ window: Window, resolvedProperties: Window.ResolvedProperties?, _ action: BoundWindowAction) {
        // If the window has not been recorded, record it
        recordFirstIfNeeded(for: window, resolvedProperties: resolvedProperties)

        // There is no point in recording undo
        guard action.direction != .undo else {
            return
        }

        if shouldStoreAsFinalFrame(action), let screen = ScreenUtility.screenContaining(window) {
            let customActionName = "autogenerated_record_\(action.getActionName())"
            let windowFrame = resolvedProperties?.frame ?? window.frame
            let adjustedBounds = PaddingConfiguration
                .getConfiguredPadding(for: screen)
                .applyToBounds(screen.cgSafeScreenFrame, screen: screen)

            let proportionalSize = CGRect(
                x: (windowFrame.minX - adjustedBounds.minX) / adjustedBounds.width,
                y: (windowFrame.minY - adjustedBounds.minY) / adjustedBounds.height,
                width: windowFrame.width / adjustedBounds.width,
                height: windowFrame.height / adjustedBounds.height
            )

            // Create custom action with percentage-based positioning and sizing
            let customAction = WindowAction.CustomWindowAction(
                name: customActionName,
                unit: .percentage,
                anchor: .topLeft,
                sizeMode: .custom,
                width: proportionalSize.width * 100,
                height: proportionalSize.height * 100,
                positionMode: .coordinates,
                xPoint: proportionalSize.minX * 100,
                yPoint: proportionalSize.minY * 100
            )

            let boundAction = BoundWindowAction(
                action: .custom(customAction),
                keybind: []
            )

            recordsByWindowID[window.cgWindowID]?.actions.insert(boundAction, at: 0)
        } else {
            recordsByWindowID[window.cgWindowID]?.actions.insert(action, at: 0)
        }

        log.info("Recorded window action for: \(window)")
    }

    /// Removes the last action performed on the specified window. This will NOT remove the first action for the specified window.
    func removeLastAction(for window: Window) {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count > 1
        else {
            log.info("Skipped removing last record for: \(window)")
            return
        }

        recordsByWindowID[window.cgWindowID]?.actions.removeFirst()

        log.info("Removed last record for: \(window)")
    }

    /// This window's last action
    /// - Parameters:
    ///   - window: Window to check
    /// - Returns: The bound window action
    func getLastAction(for window: Window) -> BoundWindowAction? {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count >= 2
        else {
            return nil
        }

        return record.actions[1]
    }

    /// This window's current recorded action
    /// - Parameters:
    ///   - window: Window to check
    /// - Returns: The bound window action
    func getCurrentAction(for window: Window) -> BoundWindowAction? {
        guard let record = recordsByWindowID[window.cgWindowID],
              record.actions.count >= 1
        else {
            return nil
        }

        return record.actions[0]
    }

    func getInitialFrame(for window: Window) -> CGRect? {
        recordsByWindowID[window.cgWindowID]?.initialFrame
    }
}
